from model_commons import ModelCommons

mc = ModelCommons()
mc.set_data_frame()
mc.check_nan()
mc.strip_spaces()
mc.feature_label_splitter()
mc.encoding_categorical()
mc.test_train_split()
mc.standard_normalization()
mc.create_score_space()
print('\n ------------------------------------------------\n')
mc.linear_classifier()
mc.calc_all_metrics()
print('\n ------------------------------------------------\n')
mc.k_nearest_neighbors()
mc.calc_all_metrics()
print('\n ------------------------------------------------\n')
mc.decision_tree_classifier()
mc.calc_all_metrics()
print('\n ------------------------------------------------\n')
mc.support_vector_classifier()
mc.calc_all_metrics()
print('\n ------------------------------------------------\n')
mc.simplest_ann_score_space()
mc.calc_all_ann_metrics()
print('\n ------------------------------------------------\n')
mc.k_nearest_reduced_features()
mc.calc_all_metrics()
