from visualizer import Visualizer

vis = Visualizer()
vis.set_data_frame()
vis.check_nan()
vis.strip_spaces()
vis.age_comparison_plot()
vis.height_comparison_plot()
vis.weight_comparison_plot()
vis.income_comparison_plot()
vis.corr_heatmap()
vis.occupational_divide()
vis.educational_divide()
vis.marital_divide()
vis.favorite_color()
vis.feature_label_splitter()
vis.encoding_categorical()
